server:
  port: 9090
spring:
  application:
    name: mobileplatform-server
  profiles:
    active:
      dev
mybatis-plus:
  mapper-locations: classpath:/mybatis/mapper/*Mapper.xml
  type-aliases-package: com.lhc.ocat.mobileplatform.domain.dos
  config-location: classpath:/mybatis/mybatis-config.xml
