platform :ios, '8.0'
use_frameworks!

target 'ios-demo' do
  pod "GCDWebServer", "~> 3.4.2"
  pod 'SSZipArchive'
  pod 'CocoaLumberjack'
  pod 'SVProgressHUD'
end


post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
               end
          end
   end
end
